"""Updated Course

Revision ID: 075c07c8167c
Revises: 
Create Date: 2021-04-07 23:34:29.713270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075c07c8167c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('par', sa.Integer(), nullable=False))
    op.drop_column('round', 'par')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('par', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('course', 'par')
    # ### end Alembic commands ###
