"""Teebox is is not nullable in Round

Revision ID: 1698645f1ef7
Revises: c8af138f0001
Create Date: 2023-07-31 16:17:32.456208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1698645f1ef7'
down_revision = 'c8af138f0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('round', 'teebox_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('round', 'teebox_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
