"""Rename Theme.color_pallete to color_palette

Revision ID: 277bcb05fff2
Revises: 30019c77f479
Create Date: 2025-05-29 14:13:02.010544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277bcb05fff2'
down_revision = '30019c77f479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_palette', sa.String(), nullable=True))
        batch_op.drop_column('color_pallete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_pallete', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('color_palette')

    # ### end Alembic commands ###
