"""Added date to round

Revision ID: 28e1f59199ba
Revises: 075c07c8167c
Create Date: 2021-04-29 00:13:16.626886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e1f59199ba'
down_revision = '075c07c8167c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'date')
    # ### end Alembic commands ###
