"""Update theme model

Revision ID: 30019c77f479
Revises: b3f338af2a98
Create Date: 2025-05-29 11:22:31.244346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30019c77f479'
down_revision = 'b3f338af2a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_contrast', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_pallete', sa.String(), nullable=True))
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('color_pallete')
        batch_op.drop_column('color_contrast')
        batch_op.drop_column('primary_color')
        batch_op.drop_column('mode')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
