"""CourseRanking.ranking to .rating

Revision ID: 4ff569583a2d
Revises: 1698645f1ef7
Create Date: 2023-08-01 11:56:42.415308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ff569583a2d'
down_revision = '1698645f1ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_ranking', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('course_ranking', 'ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_ranking', sa.Column('ranking', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('course_ranking', 'rating')
    # ### end Alembic commands ###
