"""Make Handicap.user_id unique

Revision ID: 61156387d559
Revises: 8b2a4f110d26
Create Date: 2025-07-15 16:12:30.650579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61156387d559'
down_revision = '8b2a4f110d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handicap', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handicap', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
