"""Add address to course

Revision ID: 672672368b37
Revises: 4ff569583a2d
Create Date: 2024-06-04 10:38:38.192736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672672368b37'
down_revision = '4ff569583a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
