"""Add visible toggle

Revision ID: 7c3e4e803833
Revises: e6c46b7db98f
Create Date: 2022-09-06 21:00:14.615668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3e4e803833'
down_revision = 'e6c46b7db98f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_publicly_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_publicly_visible')
    # ### end Alembic commands ###
