"""Add UniqueConstraint for CourseRanking

Revision ID: 8b2a4f110d26
Revises: 277bcb05fff2
Create Date: 2025-07-15 13:03:33.214127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2a4f110d26'
down_revision = '277bcb05fff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghin_round')
    with op.batch_alter_table('course_ranking', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_ranking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('ghin_round',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_holes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_played_holes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('slope_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tee_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('net_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pcc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('differential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unadjusted_differential', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ghin_round_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ghin_round_pkey')
    )
    # ### end Alembic commands ###
