"""Add email subscription model

Revision ID: 942f3cc59876
Revises: 0588c08b2e35
Create Date: 2023-04-24 17:27:17.577567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942f3cc59876'
down_revision = '0588c08b2e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('subscribtion_id', sa.Integer(), nullable=False))
    op.drop_constraint('subscriber_subscribed_id_fkey', 'subscriber', type_='foreignkey')
    op.create_foreign_key(None, 'subscriber', 'subscription', ['subscribtion_id'], ['id'])
    op.drop_column('subscriber', 'subscribed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('subscribed_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriber', type_='foreignkey')
    op.create_foreign_key('subscriber_subscribed_id_fkey', 'subscriber', 'subscription', ['subscribed_id'], ['id'])
    op.drop_column('subscriber', 'subscribtion_id')
    # ### end Alembic commands ###
