"""Remove teebox info from Course

Revision ID: c8af138f0001
Revises: 
Create Date: 2023-07-31 16:16:48.594712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8af138f0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'slope')
    op.drop_column('course', 'par')
    op.drop_column('course', 'rating')
    op.drop_column('course', 'teebox')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teebox', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('par', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('slope', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
