"""Add score diff to Round

Revision ID: d54e801d4609
Revises: b9d3a5ed9848
Create Date: 2022-06-05 00:42:43.778892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54e801d4609'
down_revision = 'b9d3a5ed9848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('round', sa.Column('scrore_diff', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('round', 'scrore_diff')
    # ### end Alembic commands ###
