"""Add nullable teebox to Course

Revision ID: dcca6c225899
Revises: a56692f13261
Create Date: 2023-03-15 11:30:49.647553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcca6c225899'
down_revision = 'a56692f13261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('teebox', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'teebox')
    # ### end Alembic commands ###
