"""Add 9 hole round attribute to Round

Revision ID: f1bb64eeb522
Revises: 73e215f2748a
Create Date: 2024-06-22 10:38:59.069047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bb64eeb522'
down_revision = '73e215f2748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nine_hole_round', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('nine_hole_round')

    # ### end Alembic commands ###
